# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c85ffa1acaf1212950b891a7f1a9ae5ba1b178a2979b6c772b7102f92fad70787a1dda58bdafb440ea3764d1758832f9dbf9e013feb9bdd6a9f74f3f18eb28b6

test:
  secret_key_base: d494127470a011220df2c120fc36a4ec0a6a94bae0d2eaac2b2c55d446f655fead3e856a72e4bda78c93c2f5c1d51b45d356b7ef80736674181d1f15c1525945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
